In [27]:
# dependencies
import numpy as np

## Classwork 3-01

Define a matrix $A$, find the eigendecomposition of A

Reference:

$$
AV = VD, A = VDV^{-1}
$$

$V$: matrix, $A$'s eigenvectors

$D$: vector, $A$'s eigenvalues

In [ ]:
# A = np.random.randint(0, 10, (3,3))
A = np.array(([8, 1, 6], [3, 5, 7], [4, 9, 2]))
detA = np.linalg.det(A)

# Find eigen values and eigenvectors of A and construct V and D
eigenValues, eigenVectors = np.linalg.eig(A)

V = eigenVectors
V_inv = np.linalg.inv(V)
D = np.diag(eigenValues)


if A.all() ==np.cross(np.cross(V, D), V_inv).all():
    print("[PASSED]")
else:
    print("[FAILED]")
    
print(f"""
V =
{V}

D =
{D}

-------------------

The given matrix A =
{A}
        --> [ det(A) = {detA} ]

The eigen values and eigenvectors of A are
    """)

for eigenVal, eigenVec in zip(eigenValues, eigenVectors):
    print(f"{eigenVal}\t {eigenVec}")
    


[PASSED]

V =
[[-0.57735027 -0.81305253 -0.34164801]
 [-0.57735027  0.47140452 -0.47140452]
 [-0.57735027  0.34164801  0.81305253]]

D =
[[15.          0.          0.        ]
 [ 0.          4.89897949  0.        ]
 [ 0.          0.         -4.89897949]]

-------------------

The given matrix A =
[[8 1 6]
 [3 5 7]
 [4 9 2]]
        --> [ det(A) = -359.9999999999997 ]

The eigen values and eigenvectors of A are
    
14.999999999999996	 [-0.57735027 -0.81305253 -0.34164801]
4.898979485566361	 [-0.57735027  0.47140452 -0.47140452]
-4.898979485566357	 [-0.57735027  0.34164801  0.81305253]


## Classwork 3-02

Define a matrix $A$, find the singular value decomposition of A

Reference:

$$
A = U\Sigma V^{T},
$$

$V$: $m\times m$ unitary matrix

$D$: vector, $A$'s eigenvalues

## Classwork 3-03

Generate Pascall's Triange using iterator.

In [32]:
def pascal_triange_iter():
    L = [1]
    while True:
        yield L
        L = [sum(i) for i in zip([0]+L, L+[0])]
        
a = pascal_triange_iter()

for i in range(7):
    ss = " ".join([str(d) for d in next(a)])
    print("{0:^25}".format(ss))

            1            
           1 1           
          1 2 1          
         1 3 3 1         
